### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'words')

### ISSUE THREAD

**Issue by codeallthethingz** [itemsapi/itemsjs#128] opened 2023-07-15 04:33 UTC
I'm getting the following stack trace when I pass in too many filters, 

```
FastBitSet.js:505 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'words')
    at FastBitSet.new_union (FastBitSet.js:505:57)
    at helpers.js:279:23
    at Proxy.forEach (<anonymous>)
    at helpers.js:277:13
    at lodash.js:13469:38
    at lodash.js:4967:15
    at baseForOwn (lodash.js:3032:24)
    at Function.mapValues (lodash.js:13468:7)
    at Object.facets_ids2 [as facets_ids] (helpers.js:276:5)
    at Facets2.search (facets.js:117:32)
```

I would expect to get back a zero results but still with the aggregations so I can deselect the ones that are causing issues.

**Comment by cigolpl** [comment] 2023-07-18 06:24
Thank you for reaching out to us with this issue. To better understand and reproduce the problem, could you please provide us with the following information?

1. The steps you took leading up to the issue.
2. Screenshots, if possible, that could help us understand the issue better.
3. The list of filters and their types (string, boolean, etc.) or at which filter does this error occur?

**Comment by cigolpl** [comment] 2023-08-06 17:36
I am closing this ticket due to insufficient information. Please provide more details on how we can reproduce the issue if you'd like us to reopen it

**Closed by cigolpl** 2023-08-06 17:36 UTC
